### Products Index
GET http://localhost:3000/products.json

### Products show
GET http://localhost:3000/products/1.json


### Products create
POST http://localhost:3000/products
Content-type: application/json

{
  "name": "test name",
  "price": "test price",
  "description": "test description",
  "image_url": "test image_url"
}

### Products update
PATCH http://localhost:3000/products/5
Content-type: application/json

{
  "name": "Rolex Watch",
  "price": 54654,
  "description": "A fancy watch",
  "image_url": "test image_url"
}

### Products destroy
DELETE http://localhost:3000/products/6

