@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTI4OTExMTZ9.jLaVqVOCywNtIu0h5rKmirfyb4pvm3YGHnhRLijwz_s

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
### Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Orders show
GET http://localhost:3000/orders/2
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Orders create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 1
}