@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTQ2Mjk2OTN9.7eChyM_Hin7ZHhOJ9DucY9OicN6aK7qzyqMGk7gh7uY

### Index
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": "3",
  "quantity": "4"
}

### Destroy
DELETE http://localhost:3000/carted_products/1.json
Authorization: Bearer {{ jwt }}
Content-Type: application/json