@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTMwNzI0MjN9.UpU8KbCkovUdYly8kNw6F5uFHoN75JX81oqIcXCFcW4


### Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Orders show
GET http://localhost:3000/orders/7.json
Authorization: Bearer {{jwt}}

### Orders create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 1
}