@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTQ2MzAwNDV9.ywV7-PS_Q7O1sXY9yGtsIc9J7hIHhnRS5XFOTlj_JXs

### Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### Orders show
GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}

### Orders create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 1
}