@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTI5OTI3ODd9.HLe3IBOYc6iz2jxWo4ewwL4yfn_4k_nxQNUrXtZbpHY


### Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Orders show
GET http://localhost:3000/orders/7.json
Authorization: Bearer {{jwt}}

### Orders create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 1
}