@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTQ4MDAyMjN9.QUixvpYUUf8sJqz0V08YryeggmxEZFraBQPFn-wVTmU

### Products Index
GET http://localhost:3000/products.json?search=s

### Products Index
GET http://localhost:3000/products.json?sort=price

### Products Index
GET http://localhost:3000/products.json?sort=price&sort_order=desc

### Products Index
GET http://localhost:3000/products.json?sort=price&sort_order=asc&discount=true


### Products show
GET http://localhost:3000/products/5.json


### Products create
POST http://localhost:3000/products.json
Content-type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "test name",
  "price": 123,
  "description": "test description",
  "quantity": 10,
  "supplier_id": 1
}

### Products update
PATCH http://localhost:3000/products/5.json
Content-type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Rolex Sea-Dweller",
  "price": 17000,
  "description": "A fancy watch",
  "quantity": 1
}

### Products destroy
DELETE http://localhost:3000/products/6

