### Products Index
GET http://localhost:3000/products.json


### Products show
GET http://localhost:3000/products/3.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTM2ODYyNTZ9.72kyO-u24eCxFPug6YYF2qaDM-dPT1VvhKGl_oG4sFo
Content-Type: application/json

### Products create
POST http://localhost:3000/products.json
Content-type: application/json

{
  "name": "cool",
  "price": -10,
  "description": "test",
  "image_url": "test image_url"
}

### Products update
PATCH http://localhost:3000/products/5.json
Content-type: application/json

{
  "name": "Rolex Watch",
  "price": 54654,
  "description": "A fancy watch",
  "image_url": "test image_url"
}

### Products destroy
DELETE http://localhost:3000/products/6

